import type {
  DefinitionBande,
  Equipement,
  ProfilRecrue,
  Statistiques,
} from './mordheim-data.ts';

const profil = (
  donnees: Omit<ProfilRecrue, 'statistiques'> & {
    statistiques: Parameters<typeof stats>;
  },
): ProfilRecrue => ({
  ...donnees,
  statistiques: stats(...donnees.statistiques),
});

const profilsPossedes: ProfilRecrue[] = [
  profil({
    id: 'possedes-magister',
    nom: 'Magister',
    categorie: 'Héros',
    cout: 70,
    minimum: 1,
    maximum: 1,
    experienceInitiale: 20,
    statistiques: [4, 4, 4, 3, 3, 1, 3, 1, 8],
    listesEquipement: ['possedes'],
    competencesDisponibles: ['Combat', 'Érudition', 'Vitesse'],
    chef: true,
    regleSpeciale:
      'Chef. Sorcier : utilise les Rituels du Chaos conformément aux règles de magie.',
  }),
  profil({
    id: 'possedes-possede',
    nom: 'Possédé',
    categorie: 'Héros',
    cout: 90,
    minimum: 0,
    maximum: 2,
    experienceInitiale: 8,
    statistiques: [5, 4, 0, 4, 4, 2, 4, 2, 7],
    maximums: stats(6, 8, 0, 6, 6, 4, 7, 5, 10),
    listesEquipement: ['mutations'],
    competencesDisponibles: ['Combat', 'Force', 'Vitesse'],
    regleSpeciale:
      'Cause la peur. Ne peut jamais utiliser d’arme ni d’armure. Les mutations ne peuvent être achetées qu’au recrutement.',
  }),
  profil({
    id: 'possedes-mutant',
    nom: 'Mutant',
    categorie: 'Héros',
    cout: 25,
    minimum: 0,
    maximum: 2,
    experienceInitiale: 0,
    statistiques: [4, 3, 3, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['possedes', 'mutations'],
    competencesDisponibles: ['Combat', 'Vitesse'],
    minimumMutations: 1,
    regleSpeciale:
      'Doit commencer avec au moins une mutation. Les mutations ne peuvent être achetées qu’au recrutement.',
  }),
  profil({
    id: 'possedes-ame-damnee',
    nom: 'Âme damnée',
    categorie: 'Hommes de main',
    cout: 35,
    minimum: 0,
    maximum: 5,
    experienceInitiale: 0,
    statistiques: [4, 2, 2, 4, 3, 1, 3, 1, 6],
    listesEquipement: ['ames-sombres'],
    regleSpeciale:
      'Dément : réussit automatiquement tous les tests fondés sur le Commandement.',
  }),
  profil({
    id: 'possedes-frere',
    nom: 'Frère',
    categorie: 'Hommes de main',
    cout: 25,
    minimum: 0,
    maximum: null,
    experienceInitiale: 0,
    statistiques: [4, 3, 3, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['possedes'],
  }),
  profil({
    id: 'possedes-homme-bete',
    nom: 'Homme-bête Gor',
    categorie: 'Hommes de main',
    cout: 45,
    minimum: 0,
    maximum: 3,
    experienceInitiale: 0,
    statistiques: [4, 4, 3, 3, 4, 2, 3, 1, 7],
    maximums: stats(4, 7, 6, 4, 5, 4, 6, 4, 9),
    listesEquipement: ['ames-sombres'],
  }),
];

const profilsRepurgateurs: ProfilRecrue[] = [
  profil({
    id: 'repurgateurs-capitaine',
    nom: 'Capitaine répurgateur',
    categorie: 'Héros',
    cout: 60,
    minimum: 1,
    maximum: 1,
    experienceInitiale: 20,
    statistiques: [4, 4, 4, 3, 3, 1, 4, 1, 8],
    listesEquipement: ['repurgateurs'],
    competencesDisponibles: ['Combat', 'Tir', 'Érudition', 'Force', 'Vitesse'],
    chef: true,
    regleSpeciale:
      'Chef. Brûlez la sorcière : hait tous les lanceurs de sorts.',
  }),
  profil({
    id: 'repurgateurs-repurgateur',
    nom: 'Répurgateur',
    categorie: 'Héros',
    cout: 25,
    minimum: 0,
    maximum: 3,
    experienceInitiale: 8,
    statistiques: [4, 3, 3, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['repurgateurs'],
    competencesDisponibles: ['Combat', 'Tir', 'Érudition', 'Vitesse'],
    regleSpeciale: 'Brûlez la sorcière : hait tous les lanceurs de sorts.',
  }),
  profil({
    id: 'repurgateurs-pretre',
    nom: 'Prêtre-guerrier',
    categorie: 'Héros',
    cout: 40,
    minimum: 0,
    maximum: 1,
    experienceInitiale: 12,
    statistiques: [4, 3, 3, 3, 3, 1, 3, 1, 8],
    listesEquipement: ['repurgateurs'],
    competencesDisponibles: ['Combat', 'Érudition', 'Force'],
    regleSpeciale:
      'Utilise les Prières de Sigmar conformément aux règles de magie.',
  }),
  profil({
    id: 'repurgateurs-flagellant',
    nom: 'Flagellant',
    categorie: 'Hommes de main',
    cout: 40,
    minimum: 0,
    maximum: 5,
    experienceInitiale: 0,
    statistiques: [4, 3, 3, 4, 4, 1, 3, 1, 10],
    listesEquipement: ['flagellants'],
    regleSpeciale:
      'Fanatique : réussit automatiquement tous les tests fondés sur le Commandement, ne peut jamais devenir chef et ne peut utiliser aucune arme de tir, même s’il obtient plus tard l’accès à cette catégorie.',
  }),
  profil({
    id: 'repurgateurs-zelote',
    nom: 'Zélote',
    categorie: 'Hommes de main',
    cout: 20,
    minimum: 0,
    maximum: null,
    experienceInitiale: 0,
    statistiques: [4, 2, 2, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['zelotes'],
  }),
  profil({
    id: 'repurgateurs-chien',
    nom: 'Chien de guerre',
    categorie: 'Hommes de main',
    cout: 15,
    minimum: 0,
    maximum: 5,
    experienceInitiale: 0,
    statistiques: [6, 4, 0, 4, 3, 1, 4, 1, 5],
    listesEquipement: [],
    gagneExperience: false,
    regleSpeciale:
      'Animal : utilise ses crocs et ne gagne jamais d’expérience.',
  }),
];

const profilsSoeurs: ProfilRecrue[] = [
  profil({
    id: 'soeurs-matriarche',
    nom: 'Matriarche sigmarite',
    categorie: 'Héros',
    cout: 70,
    minimum: 1,
    maximum: 1,
    experienceInitiale: 20,
    statistiques: [4, 4, 4, 3, 3, 1, 4, 1, 8],
    listesEquipement: ['soeurs'],
    competencesDisponibles: [
      'Combat',
      'Érudition',
      'Force',
      'Vitesse',
      'Spécial',
    ],
    chef: true,
    regleSpeciale:
      'Chef. Utilise les Prières de Sigmar conformément aux règles de magie.',
  }),
  profil({
    id: 'soeurs-superieure',
    nom: 'Sœur supérieure',
    categorie: 'Héros',
    cout: 35,
    minimum: 0,
    maximum: 3,
    experienceInitiale: 8,
    statistiques: [4, 4, 3, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['soeurs'],
    competencesDisponibles: [
      'Combat',
      'Érudition',
      'Force',
      'Vitesse',
      'Spécial',
    ],
  }),
  profil({
    id: 'soeurs-augure',
    nom: 'Augure',
    categorie: 'Héros',
    cout: 25,
    minimum: 0,
    maximum: 1,
    experienceInitiale: 0,
    statistiques: [4, 2, 2, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['augure'],
    competencesDisponibles: ['Érudition', 'Vitesse', 'Spécial'],
    regleSpeciale:
      'Vue bénie : relance les tests de caractéristique et les jets pour toucher ; lance deux dés d’exploration et en conserve un si elle n’est pas hors de combat. Ne porte jamais d’armure.',
  }),
  profil({
    id: 'soeurs-sigmarite',
    nom: 'Sœur sigmarite',
    categorie: 'Hommes de main',
    cout: 25,
    minimum: 0,
    maximum: null,
    experienceInitiale: 0,
    statistiques: [4, 3, 3, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['soeurs'],
  }),
  profil({
    id: 'soeurs-novice',
    nom: 'Novice',
    categorie: 'Hommes de main',
    cout: 15,
    minimum: 0,
    maximum: 10,
    experienceInitiale: 0,
    statistiques: [4, 2, 2, 3, 3, 1, 3, 1, 6],
    listesEquipement: ['soeurs'],
  }),
];

const profilsMortsVivants: ProfilRecrue[] = [
  profil({
    id: 'morts-vivants-vampire',
    nom: 'Vampire',
    categorie: 'Héros',
    cout: 110,
    minimum: 1,
    maximum: 1,
    experienceInitiale: 20,
    statistiques: [6, 4, 4, 4, 4, 2, 5, 2, 8],
    maximums: stats(6, 8, 6, 7, 6, 4, 9, 4, 10),
    listesEquipement: ['morts-vivants'],
    competencesDisponibles: ['Combat', 'Érudition', 'Force', 'Vitesse'],
    chef: true,
    regleSpeciale:
      'Chef. Cause la peur. Immunisé à la psychologie et au poison. Insensible à la douleur : traite « sonné » comme « à terre ».',
  }),
  profil({
    id: 'morts-vivants-necromancien',
    nom: 'Nécromancien',
    categorie: 'Héros',
    cout: 35,
    minimum: 0,
    maximum: 1,
    experienceInitiale: 8,
    statistiques: [4, 3, 3, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['morts-vivants'],
    competencesDisponibles: ['Érudition', 'Vitesse'],
    regleSpeciale:
      'Sorcier : utilise la Nécromancie conformément aux règles de magie.',
  }),
  profil({
    id: 'morts-vivants-paria',
    nom: 'Paria',
    categorie: 'Héros',
    cout: 20,
    minimum: 0,
    maximum: 3,
    experienceInitiale: 0,
    statistiques: [4, 2, 2, 3, 3, 1, 3, 1, 7],
    listesEquipement: ['morts-vivants'],
    competencesDisponibles: ['Combat', 'Force'],
  }),
  profil({
    id: 'morts-vivants-zombie',
    nom: 'Zombie',
    categorie: 'Hommes de main',
    cout: 15,
    minimum: 0,
    maximum: null,
    experienceInitiale: 0,
    statistiques: [4, 2, 0, 3, 3, 1, 1, 1, 5],
    listesEquipement: [],
    gagneExperience: false,
    regleSpeciale:
      'Cause la peur. Ne peut pas courir. Immunisé à la psychologie et au poison. Insensible à la douleur. N’utilise aucun équipement et ne gagne jamais d’expérience.',
  }),
  profil({
    id: 'morts-vivants-goule',
    nom: 'Goule',
    categorie: 'Hommes de main',
    cout: 40,
    minimum: 0,
    maximum: null,
    experienceInitiale: 0,
    statistiques: [4, 2, 2, 3, 4, 1, 3, 2, 5],
    maximums: stats(5, 5, 2, 4, 5, 3, 5, 5, 7),
    listesEquipement: [],
    regleSpeciale:
      'Cause la peur. Combat avec ses griffes et n’utilise aucun équipement.',
  }),
  profil({
    id: 'morts-vivants-loup',
    nom: 'Loup funeste',
    categorie: 'Hommes de main',
    cout: 50,
    minimum: 0,
    maximum: 5,
    experienceInitiale: 0,
    statistiques: [9, 3, 0, 4, 3, 1, 2, 1, 4],
    listesEquipement: [],
    gagneExperience: false,
    regleSpeciale:
      'Deux Attaques en charge. Ne peut pas courir. Cause la peur, immunisé à la psychologie et au poison, insensible à la douleur. N’utilise aucun équipement et ne gagne jamais d’expérience.',
  }),
];

const profilsSkavens: ProfilRecrue[] = [
  profil({
    id: 'skavens-adepte',
    nom: 'Adepte assassin',
    categorie: 'Héros',
    cout: 60,
    minimum: 1,
    maximum: 1,
    experienceInitiale: 20,
    statistiques: [6, 4, 4, 4, 3, 1, 5, 1, 7],
    maximums: stats(6, 6, 6, 4, 4, 3, 7, 4, 7),
    listesEquipement: ['skavens-heros'],
    competencesDisponibles: [
      'Combat',
      'Tir',
      'Érudition',
      'Force',
      'Vitesse',
      'Spécial',
    ],
    chef: true,
    regleSpeciale:
      'Chef. Tueur parfait : inflige un modificateur supplémentaire de -1 à la sauvegarde des blessures causées au tir ou au corps à corps.',
  }),
  profil({
    id: 'skavens-noir',
    nom: 'Skaven noir',
    categorie: 'Héros',
    cout: 40,
    minimum: 0,
    maximum: 2,
    experienceInitiale: 8,
    statistiques: [6, 4, 3, 4, 3, 1, 5, 1, 6],
    maximums: stats(6, 6, 6, 4, 4, 3, 7, 4, 7),
    listesEquipement: ['skavens-heros'],
    competencesDisponibles: ['Combat', 'Tir', 'Force', 'Vitesse', 'Spécial'],
  }),
  profil({
    id: 'skavens-sorcier',
    nom: 'Sorcier Eshin',
    categorie: 'Héros',
    cout: 45,
    minimum: 0,
    maximum: 1,
    experienceInitiale: 8,
    statistiques: [5, 3, 3, 3, 3, 1, 4, 1, 6],
    maximums: stats(6, 6, 6, 4, 4, 3, 7, 4, 7),
    listesEquipement: ['skavens-heros'],
    competencesDisponibles: ['Érudition', 'Vitesse', 'Spécial'],
    regleSpeciale: 'Sorcier : utilise la Magie du Rat Cornu.',
  }),
  profil({
    id: 'skavens-coureur',
    nom: 'Coureur nocturne',
    categorie: 'Héros',
    cout: 20,
    minimum: 0,
    maximum: 2,
    experienceInitiale: 0,
    statistiques: [6, 2, 3, 3, 3, 1, 4, 1, 4],
    maximums: stats(6, 6, 6, 4, 4, 3, 7, 4, 7),
    listesEquipement: ['skavens-hommes-main'],
    competencesDisponibles: ['Combat', 'Tir', 'Spécial'],
  }),
  profil({
    id: 'skavens-vermine',
    nom: 'Verminkin',
    categorie: 'Hommes de main',
    cout: 20,
    minimum: 0,
    maximum: null,
    experienceInitiale: 0,
    statistiques: [5, 3, 3, 3, 3, 1, 4, 1, 5],
    maximums: stats(6, 6, 6, 4, 4, 3, 7, 4, 7),
    listesEquipement: ['skavens-hommes-main'],
  }),
  profil({
    id: 'skavens-rat-geant',
    nom: 'Rat géant',
    categorie: 'Hommes de main',
    cout: 15,
    minimum: 0,
    maximum: null,
    experienceInitiale: 0,
    statistiques: [6, 2, 0, 3, 3, 1, 4, 1, 4],
    listesEquipement: [],
    gagneExperience: false,
    regleSpeciale:
      'Animal : n’utilise aucun équipement et ne gagne jamais d’expérience.',
  }),
  profil({
    id: 'skavens-rat-ogre',
    nom: 'Rat-ogre',
    grandeCreature: true,
    categorie: 'Hommes de main',
    cout: 210,
    minimum: 0,
    maximum: 1,
    experienceInitiale: 0,
    statistiques: [6, 3, 3, 5, 5, 3, 4, 3, 4],
    listesEquipement: [],
    gagneExperience: false,
    regleSpeciale:
      'Cause la peur. Stupide sauf si un Héros skaven se trouve à 6 ps. Grande cible. N’utilise aucun équipement et ne gagne jamais d’expérience.',
  }),
];

export const profilsBandesCore = [
  ...profilsPossedes,
  ...profilsRepurgateurs,
  ...profilsSoeurs,
  ...profilsMortsVivants,
  ...profilsSkavens,
];

export const equipementsBandesCore: Equipement[] = [
  equipement('fleau', 'Fléau', 'Corps à corps', 15, [
    'ames-sombres',
    'flagellants',
    'soeurs',
    'augure',
    'skavens-heros',
  ]),
  {
    ...equipement('arc-court', 'Arc court', 'Tir', 5, [
      'possedes',
      'zelotes',
      'morts-vivants',
    ]),
    coutsParListe: { possedes: 10 },
  },
  {
    ...equipement(
      'arbalete-pistolet',
      'Arbalète de poing',
      'Tir',
      35,
      ['repurgateurs'],
      'Portée 10 ps, F4. Peut tirer au premier round de corps à corps avec -2 pour toucher, avant les autres attaques.',
    ),
    rareteCommerce: 9,
  },
  equipement('fronde', 'Fronde', 'Tir', 2, [
    'soeurs',
    'augure',
    'skavens-heros',
    'skavens-hommes-main',
  ]),
  {
    ...equipement(
      'marteau-sigmarite',
      'Marteau sigmarite',
      'Corps à corps',
      15,
      ['soeurs', 'augure'],
      'Force utilisateur +1. Commotion. Arme sainte : +1 pour blesser les Possédés et les Morts-Vivants. Seules la Matriarche et les Sœurs supérieures peuvent en porter deux.',
    ),
    quantiteMax: 1,
    quantitesMaxParProfil: {
      'soeurs-matriarche': 2,
      'soeurs-superieure': 2,
      'soeurs-augure': 1,
      'soeurs-novice': 1,
    },
  },
  equipement(
    'fouet-acier',
    'Fouet d’acier',
    'Corps à corps',
    10,
    ['soeurs', 'augure'],
    'Ne peut pas être paré. Coup de fouet : +1 Attaque en charge ou contre le chargeur.',
  ),
  {
    ...equipement(
      'tome-sacre',
      'Tome sacré',
      'Divers',
      120,
      ['soeurs', 'augure'],
      '',
      true,
    ),
    rareteCommerce: 8,
    coutCommerceFormule: '100 + 1D6 × 10 CO',
  },
  equipement(
    'eau-benite',
    'Eau bénite',
    'Divers',
    10,
    ['soeurs', 'augure'],
    '',
    true,
  ),
  {
    ...equipement(
      'relique-sainte',
      'Relique sainte',
      'Divers',
      15,
      ['soeurs', 'augure'],
      '',
      true,
    ),
    rareteCommerce: 6,
    coutCommerceFormule: '15 + 3D6 CO',
  },
  {
    ...equipement('etoiles-jet', 'Étoiles de jet', 'Tir', 15, [
      'skavens-heros',
    ]),
    rareteCommerce: 5,
  },
  {
    ...equipement(
      'sarbacane',
      'Sarbacane',
      'Tir',
      25,
      ['skavens-heros'],
      'Portée 8 ps, F1, sauvegarde +1. Un 6 pour toucher blesse automatiquement et l’arme ne cause aucun coup critique. Un tireur caché reste caché après le tir, sauf si la cible réussit un test d’Initiative pour le repérer.',
    ),
    rareteCommerce: 7,
  },
  {
    ...equipement(
      'pistolet-malepierre',
      'Pistolet à malepierre',
      'Tir',
      35,
      ['skavens-heros'],
      'Portée 8 ps, F5, sauvegarde -3 ; tire un tour sur deux.',
    ),
    quantiteMax: 2,
    rareteCommerce: 11,
  },
  {
    ...equipement(
      'lames-suintantes',
      'Lames suintantes (paire)',
      'Corps à corps',
      50,
      ['skavens-heros'],
      'La paire donne +1 Attaque. Elle emploie les effets du Lotus noir, ne peut recevoir aucun autre poison et permet de parer comme des épées.',
    ),
    rareteCommerce: 9,
  },
  {
    ...equipement(
      'griffes-combat',
      'Griffes de combat (paire)',
      'Corps à corps',
      35,
      ['skavens-heros'],
      'Paire : +1 Attaque. +1 en Initiative pour grimper, parade avec une relance ; aucune autre arme pendant la bataille.',
    ),
    rareteCommerce: 7,
  },
  mutation(
    'mutation-ame-demon',
    'Âme démoniaque',
    20,
    'Sauvegarde de 4+ contre les sorts et prières.',
  ),
  mutation(
    'mutation-grande-pince',
    'Grande pince',
    50,
    '+1 Attaque avec +1 Force ; cette main ne peut porter aucune arme.',
  ),
  mutation('mutation-sabots-fendus', 'Sabots fendus', 40, '+1 Mouvement.'),
  mutation(
    'mutation-queue-scorpion',
    'Queue de scorpion',
    40,
    'Une attaque supplémentaire de Force 5 ; Force 2 contre une cible immunisée au poison.',
  ),
  mutation(
    'mutation-bras-supplementaire',
    'Bras supplémentaire',
    40,
    'Peut porter une arme à une main, un bouclier ou une rondache ; un Possédé gagne une Attaque supplémentaire.',
  ),
  mutation('mutation-hideux', 'Hideux', 40, 'Cause la peur.'),
  mutation(
    'mutation-tentacule',
    'Tentacule',
    35,
    'Retire une Attaque à un adversaire au contact, jusqu’à un minimum de 1.',
  ),
  mutation(
    'mutation-sang-noir',
    'Sang noir',
    30,
    'Quand le mutant perd un PV au corps à corps, les figurines au contact subissent une touche F3 sans critique.',
  ),
  mutation(
    'mutation-epines',
    'Épines',
    35,
    'Toute figurine au contact subit une touche F1 automatique au début du corps à corps, sans critique.',
  ),
];

export const definitionsBandesCore: DefinitionBande[] = [
  definition(
    'culte-des-possedes',
    'Culte des Possédés',
    15,
    profilsPossedes,
    [
      [
        'Mutations',
        'Les Possédés peuvent acheter des mutations au recrutement ; les Mutants doivent en recevoir au moins une. La deuxième mutation et les suivantes coûtent le double.',
      ],
      [
        'Allégeance au Chaos',
        'Le Magister utilise les Rituels du Chaos et les Possédés causent la peur.',
      ],
    ],
    'Livre des bandes, pp. 9–13',
  ),
  definition(
    'repurgateurs',
    'Répurgateurs',
    12,
    profilsRepurgateurs,
    [
      ['Effectif restreint', 'La bande ne peut jamais dépasser 12 guerriers.'],
      [
        'Brûlez la sorcière',
        'Le Capitaine et les Répurgateurs haïssent tous les lanceurs de sorts.',
      ],
      [
        'Prières de Sigmar',
        'Le Prêtre-guerrier utilise les Prières de Sigmar.',
      ],
    ],
    'Livre des bandes, pp. 14–17',
  ),
  definition(
    'soeurs-de-sigmar',
    'Sœurs de Sigmar',
    15,
    profilsSoeurs,
    [
      ['Prières de Sigmar', 'La Matriarche utilise les Prières de Sigmar.'],
      [
        'Compétences spéciales',
        'Les Héroïnes ont accès aux compétences Signe de Sigmar, Protection de Sigmar, Détermination absolue, Fureur vertueuse et Foi absolue selon leur profil.',
      ],
      [
        'Armes de l’Ordre',
        'Le marteau sigmarite et le fouet d’acier suivent leurs règles spéciales officielles.',
      ],
    ],
    'Livre des bandes, pp. 18–21',
  ),
  definition(
    'morts-vivants',
    'Morts-Vivants',
    15,
    profilsMortsVivants,
    [
      [
        'Maître vampire',
        'La bande doit toujours être menée par exactement un Vampire.',
      ],
      [
        'Créatures mortes-vivantes',
        'Les immunités, la peur, l’insensibilité à la douleur et les restrictions de course ou d’expérience sont indiquées sur chaque profil.',
      ],
      ['Nécromancie', 'Le Nécromancien utilise les sorts de Nécromancie.'],
    ],
    'Livre des bandes, pp. 22–25',
  ),
  definition(
    'skavens-du-clan-eshin',
    'Skavens du Clan Eshin',
    20,
    profilsSkavens,
    [
      ['Horde skaven', 'La bande peut compter jusqu’à 20 guerriers.'],
      [
        'Arts d’Eshin',
        'Les Héros ont accès aux compétences Faim noire, Combat caudal, Coureur des murs, Infiltration et Art de la mort silencieuse selon leur profil.',
      ],
      [
        'Arsenal skaven',
        'Les armes exclusives d’Eshin suivent leurs règles officielles de paire, poison, parade, escalade et tir.',
      ],
    ],
    'Livre des bandes, pp. 26–31',
  ),
];

function definition(
  id: DefinitionBande['id'],
  nom: string,
  effectifMaximum: number,
  profils: ProfilRecrue[],
  regles: Array<[string, string]>,
  source: string,
): DefinitionBande {
  return {
    id,
    nom,
    slug: id,
    budgetInitial: 500,
    effectifMinimum: 3,
    effectifMaximum,
    profils,
    regles: regles.map(([titre, description]) => ({ titre, description })),
    source,
  };
}

function equipement(
  id: string,
  nom: string,
  categorie: Equipement['categorie'],
  cout: number,
  listesEquipement: Equipement['listesEquipement'],
  regleSpeciale = '',
  reserveAuxHeros = false,
): Equipement {
  return {
    id,
    nom,
    categorie,
    cout,
    listesEquipement,
    ...(regleSpeciale ? { regleSpeciale } : {}),
    ...(reserveAuxHeros ? { reserveAuxHeros: true } : {}),
  };
}

function mutation(
  id: string,
  nom: string,
  cout: number,
  regleSpeciale: string,
) {
  return equipement(id, nom, 'Mutation', cout, ['mutations'], regleSpeciale);
}

function stats(
  mouvement: number,
  capaciteCombat: number,
  capaciteTir: number,
  force: number,
  endurance: number,
  pointsVie: number,
  initiative: number,
  attaques: number,
  commandement: number,
): Statistiques {
  return {
    mouvement,
    capaciteCombat,
    capaciteTir,
    force,
    endurance,
    pointsVie,
    initiative,
    attaques,
    commandement,
  };
}
